services:
  postgresql-zskarte:
    image: postgres:16
    container_name: postgresql-zskarte
    restart: unless-stopped
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./packages/server/init:/docker-entrypoint-initdb.d
    ports:
      - 55432:5432
    environment:
      - POSTGRES_PASSWORD=supersecret123
      - POSTGRES_DB=zskarte
    networks:
      - zskarte

  pgadmin-zskarte:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-zskarte
    restart: unless-stopped
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
      - ./packages/server/init/servers.json:/pgadmin4/servers.json
    ports:
      - 7050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=info@zskarte.ch
      - PGADMIN_DEFAULT_PASSWORD=zskarte
    networks:
      - zskarte

networks:
  zskarte:
    driver: bridge