name: PR

on:
  pull_request:
    branches:
      - '**'

env:
  NODE_VERSION: 20.x

jobs:
  testAndBuild:
    name: Test and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      # - name: Test
      #   run: yarn test
      #   env:
      #     CI: 'true'

      - name: Build
        run: yarn build

      - name: Store Playwright's Version
        run: |
          PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')
          echo "Playwright's Version: $PLAYWRIGHT_VERSION"
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      - name: Cache Playwright Browsers for Playwright's Version
        id: cache-playwright-browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}

      - name: Setup Playwright
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
