name: PR

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - synchronize

env:
  NODE_VERSION: 20.x

jobs:
  testAndBuild:
    name: Test and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm instal

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint
